.TH TELEPATH 1 "BUILDDATE" "Version VERSION" "User Commands"
.SH NAME
telepath \- is a powerful CLI tool for secure port forwarding with support for multiple jump hosts and flexible authentication.
.SH SYNOPSIS
.B telepath
.RI [ options ] [file]
.SH DESCRIPTION
Telepath is a modern, intelligent CLI tool for seamless and secure port forwarding.
Designed with versatility and ease of use in mind, Telepath enables developers and system administrators to create complex forwarding paths across multiple hosts effortlessly.
Whether you're working with password-based or keyfile authentication, single or multiple jump hosts, Telepath has you covered.

.PP
\fBUsage\fP:

.EX
telepath [global options] [file]
.EE


.SH COMMANDS
.PP
\fB--config-file, -f\fP [path of config file.]

.SH EXAMPLES
.TP
telepath --config-file=/etc/telepath/config.json
.TP
telepath -f /etc/telepath/config.json

.SH SEE ALSO
.BR gozen (1),
.BR chatz (1),
.SH AUTHOR
Written by tech-thinker, as part of the `telepath` project.
